package dao;

import models.Appointment;
import util.DBConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class AppointmentDAO {

    // 1. Method to register a new appointment (INSERT)
    public boolean registerAppointment(Appointment appointment) {
        String sql = "INSERT INTO appointments (appointment_no, patient_name, address, contact_number, dentist_name, treatment_type, appointment_date, appointment_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        // Using try-with-resources to automatically close the database connection
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            // Set the values using the getters automatically generated by Lombok
            stmt.setString(1, appointment.getAppointmentNo());
            stmt.setString(2, appointment.getPatientName());
            stmt.setString(3, appointment.getAddress());
            stmt.setString(4, appointment.getContactNumber());
            stmt.setString(5, appointment.getDentistName());
            stmt.setString(6, appointment.getTreatmentType());
            stmt.setString(7, appointment.getAppointmentDate());
            stmt.setString(8, appointment.getAppointmentTime());

            // Execute the insert command
            int rowsAffected = stmt.executeUpdate();
            return rowsAffected > 0; // Returns true if the data was saved successfully

        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
            return false;
        }
    }

    // 2. Method to display/search appointment details (SELECT)
    public Appointment getAppointmentByNumber(String appointmentNo) {
        String sql = "SELECT * FROM appointments WHERE appointment_no = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, appointmentNo);
            ResultSet rs = stmt.executeQuery();

            // If a record is found, map it back to an Appointment Java object
            if (rs.next()) {
                return new Appointment(
                        rs.getString("appointment_no"),
                        rs.getString("patient_name"),
                        rs.getString("address"),
                        rs.getString("contact_number"),
                        rs.getString("dentist_name"),
                        rs.getString("treatment_type"),
                        rs.getString("appointment_date"),
                        rs.getString("appointment_time")
                );
            }

        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }

        return null; // Return null if no appointment is found
    }
}